version: '3'

services:
  server:
    container_name: calendron-server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5001:5001
    env_file:
      - .env
